components_configurations_folder: ~/w/ros2_ws/src/localization_performance_modelling/config/component_configurations
gazebo_model_path_env_var: [~/w/ros2_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/]
gazebo_plugin_path_env_var: [~/w/ros2_ws/build/gazebo_plugins/]

supervisor_component: localization_benchmark_supervisor

components_configuration:
  supervisor: localization_benchmark_supervisor/localization_benchmark_supervisor.yaml
  nav2_amcl: nav2_amcl/nav2_amcl_1.yaml
  nav2_navigation: nav2_navigation/nav2_navigation_1.yaml
  rviz: rviz/nav2_default_view.rviz

combinatorial_parameters:
  beta: [[0.0175, 0.0175, 0.005, 0.005], [0.035, 0.035, 0.01, 0.01], [0.07, 0.07, 0.02, 0.02]]
  laser_scan_max_range: [3.5, 5.0, 8.0, 30.0]
  laser_scan_fov_deg: [90, 180, 270, 360]
